baseURL = "/"
theme = "terminal7-theme"
languageCode = "en-us"

title = "Terminal7"

paginate = 3

[params]
  title = "Terminal7"
  description = "To boldly go where no terminal has gone before"
  images = []
  copyright = "copyright (c) tuzig LTD"

[taxonomies]
  series = "series"

[menu]
  [[menu.main]]
    name = "github"
    url = "https://github.com/tuzig/terminal7"
    weight = 100

  [[menu.main]]
    name = "discord"
    url = "https://discord.com/invite/rDBj8k4tUE"
    weight = 200

  [[menu.main]]
    name = "twitter"
    url = "https://twitter.com/7terminal"
    weight = 300

